### PR TITLE
Add editorconfig file

### PR DESCRIPTION
**Pull request by vinibeloni**
Hello,

I was looking for repos to contribute when I found this project.
I believe it's good practice in .NET projects to have a code style (whatever it is), so I tried to adapt this file to the project's convention.

So I hope this contribution helps.

### CODE REVIEW

**Comment by arthurits** [comment]
Hi @vinibeloni!

Thanks so much for your contribution. It really helps, and having some sort of code style in the repo is positive.

I'm no expert in `.editorconfig` but these are my main concerns (probably due to my poor knowledge about this subject) refraining me to merge your PR. Maybe you could shed some light on these:

* I've generated the `.editorconfig` from my local project using Visual Studio (where I've already set my coding preferences), and I've found several differences with your proposal.
* Your fix format commit contains some modifications that I'm not comfortable with. For instance, I like to use the `this` keyword when addressing controls, and I also like to avoid braces for single-line blocks.

**Comment by vinibeloni** [comment]
> I'm no expert in `.editorconfig` but these are my main concerns (probably due to my poor knowledge about this subject) refraining me to merge your PR. Maybe you could shed some light on these:

Basically you can use `dotnet format` on terminal to apply your preferences, if you have some script or docker file, you can use `dotnet format --verify-no-changes` to check the code style in the build.

exemple:
```dockerfile
RUN dotnet restore
RUN dotnet format --verify-no-changes
RUN dotnet build -c Release --no-restore
RUN dotnet test -c Release --no-build
RUN dotnet publish ./src/*.csproj -c Release --no-build -o /app/publish 
```

If you have the `.editorconfig` file, Visual Studio/Visual Code will use it by default.

**Comment by vinibeloni** [comment]
See the new changes, because the style of the code is not standard, when I run `dotnet format` some curious things happen:

- fields with prefix `_somefield` add `this`
- some if statements without braces, now they have
- etc

if you need more information [see this post of Microsoft](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/)

**Comment by arthurits** [comment]
Hi again @vinibeloni,

I really appreciate you bringing this issue up. For the time being, I'd rather stay away from merging the format fixes in your PR. They certainly add consistency to code files, but they somewhat interfere with the (picky) way I'm used to write C# code.

I'm very glad you brought up the `.editorconfig` issue as well as your sensible arguments for its inclusion in the project. One way or another I'll probably end including such a file in the foreseeable future, based on your proposal and my own preferences.

Althought I'm closing this PR without merging it, yours was certainly a positive and substantial contribution to the project.

**Pull request closed without merging**
