### PR TITLE
strings.ja-jp.resx

### PR DESCRIPTION
**Pull request by theadityaagnihotri**
created japanese translations

### CODE REVIEW

**Review by arthurits — COMMENTED** [review]
Hi @theadityaagnihotri. Thanks for your quick translation.
However, is it possible that you took a previous base file to work with?
The file [`strings.resx`](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/strings.resx) contains 185 strings, some of which are missing in your PR.

**Comment by theadityaagnihotri** [comment]
Hii
I could not find base file strings.resx, therefore used the bangla translation file

**Comment by arthurits** [comment]
> Hii I could not find base file strings.resx, therefore used the bangla translation file

The correct file link is provided in issue description #9: [`strings.resx`](https://github.com/arthurits/ErgoLux/blob/master/ErgoLux/localization/strings.resx).
The Bangla translation (as well as some others) was done before I detected there were some strings missings.
I'll be glad if you use start from the correct base file.

**Review by arthurits — APPROVED** [review]

**Comment by arthurits** [comment]
Hi @theadityaagnihotri,
I've going through your translation. Unofrtunately I found the strings not translated starting from line 525 (the "Hausdorff-Besikovich" message box text). Your previous commit had these strings translated, but with many Bangla charecters inside the Japanese translation. I did my best, but I'm no expert in Japanase.

It would be nice if you could verify whether my modifications need some corrections or not.

**Comment by theadityaagnihotri** [comment]
I have translated the remaining strings, you can check and merge the PR

**Review by arthurits — APPROVED** [review]

**Pull request merged**
